<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\TreeNode;
use App\Services\TreeService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class TreeNodeController extends Controller
{
    public function __construct(
        private TreeService $treeService
    ) {
    }

    /**
     * Display all tree nodes.
     */
    public function index()
    {
        $nodes = $this->treeService
            ->getAllNodes()
            ->sortBy('value')
            ->values();

        return view(
            'dashboard.tree_nodes.index',
            compact('nodes')
        );
    }

    /**
     * Show create form.
     */
    public function create()
    {
        $nodes = $this->treeService
            ->getAllNodes()
            ->sortBy('ilevel')
            ->values();

        return view(
            'dashboard.tree_nodes.create',
            compact('nodes')
        );
    }

    /**
     * Store a new node.
     *
     * VALUE is generated automatically by the Oracle trigger.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'LABEL' => [
                'required',
                'string',
                'max:100',
            ],

            'LABEL_ENG' => [
                'nullable',
                'string',
                'max:100',
            ],

            'PARENT_VALUE' => [
                'nullable',
                'integer',
                Rule::exists('oracle.ERP_SYSTEM_TREE', 'VALUE'),
            ],

            'NODE_TYPE' => [
                'nullable',
                'string',
                'max:100',
            ],

            'ISTATE' => ['nullable', 'integer'],
            'REDA' => ['nullable', 'integer'],
            'SYS_TYPE' => ['nullable', 'integer'],
            'OBJ_NAME' => ['nullable', 'string', 'max:100'],
            'FORM_CODE' => ['nullable', 'integer'],
            'PAGE_ID' => ['nullable', 'integer'],
            'BRANCH_CODE' => ['nullable', 'integer'],
            'IS_SHORT' => ['nullable', 'integer'],
        ]);

        $parent = null;

        if (!empty($validated['PARENT_VALUE'])) {
            $parent = $this->treeService->getNode(
                (string) $validated['PARENT_VALUE']
            );

            if (!$parent) {
                return back()
                    ->withErrors([
                        'PARENT_VALUE' => 'The selected parent does not exist.',
                    ])
                    ->withInput();
            }
        }

        $node = new TreeNode();

        // VALUE is generated by the Oracle trigger.
        // Do NOT assign VALUE manually.

        $node->label = $validated['LABEL'];
        $node->label_eng = $validated['LABEL_ENG'] ?? null;

        $node->parent_value = $parent?->value;

        $node->ilevel = $parent
            ? ((int) $parent->ilevel + 1)
            : 1;

        /*
         * These fields are kept for compatibility with
         * the existing ERP table.
         */
        foreach ([
            'NODE_TYPE',
            'ISTATE',
            'REDA',
            'SYS_TYPE',
            'OBJ_NAME',
            'FORM_CODE',
            'PAGE_ID',
            'BRANCH_CODE',
            'IS_SHORT',
        ] as $field) {
            $lowerField = strtolower($field);

            $node->{$lowerField} = $validated[$field] ?? null;
        }

        $node->save();

        return redirect()
            ->route('admin.tree-nodes.index')
            ->with('success', 'Tree node created successfully.');
    }

    /**
     * Show a specific node.
     */
    public function show(string $id)
    {
        $node = $this->treeService->getNode($id);

        abort_if(!$node, 404);

        return view(
            'dashboard.tree_nodes.show',
            compact('node')
        );
    }

    /**
     * Show edit form.
     */
    public function edit(string $id)
    {
        $node = $this->treeService->getNode($id);

        if (!$node) {
            abort(404, 'Tree node not found.');
        }

        /*
         * The actual root is VALUE = 1000000.
         */
        if ((string) $node->value === '1000000') {
            abort(403, 'Root node cannot be edited.');
        }

        /*
         * All nodes except the current node can initially
         * appear as possible parents.
         *
         * The update method performs the important
         * descendant/cycle validation.
         */
        $parents = $this->treeService
            ->getAllNodes()
            ->filter(function ($item) use ($node) {
                return (string) $item->value !== (string) $node->value;
            })
            ->values();

        return view(
            'dashboard.tree_nodes.edit',
            compact('node', 'parents')
        );
    }

    /**
     * Update a node and recalculate levels of all descendants.
     */
    public function update(Request $request, string $id)
    {
        $node = $this->treeService->getNode($id);

        if (!$node) {
            abort(404, 'Tree node not found.');
        }

        /*
         * Protect the actual root.
         */
        if ((string) $node->value === '1000000') {
            abort(403, 'Root node cannot be edited.');
        }

        $validated = $request->validate([
            'label' => [
                'required',
                'string',
                'max:100',
            ],

            'label_eng' => [
                'nullable',
                'string',
                'max:100',
            ],

            'parent_value' => [
                'required',
                'integer',
                Rule::exists('oracle.ERP_SYSTEM_TREE', 'VALUE'),
            ],
        ]);

        $newParentValue = (string) $validated['parent_value'];
        $nodeValue = (string) $node->value;

        /*
         * Prevent assigning the node itself as its parent.
         */
        if ($newParentValue === $nodeValue) {
            return back()
                ->withErrors([
                    'parent_value' => 'A node cannot be its own parent.',
                ])
                ->withInput();
        }

        /*
         * Get all nodes directly from Oracle.
         *
         * We intentionally use the database here instead
         * of relying only on TreeService cache because
         * the hierarchy is about to change.
         */
        $allNodes = DB::connection('oracle')
            ->table('ERP_SYSTEM_TREE')
            ->get();

        /*
         * Find the selected parent.
         */
        $parent = $allNodes->first(
            fn ($item) =>
                (string) $item->value === $newParentValue
        );

        if (!$parent) {
            return back()
                ->withErrors([
                    'parent_value' => 'The selected parent does not exist.',
                ])
                ->withInput();
        }

        /*
         * Build children map.
         *
         * parent_value => children
         */
        $childrenMap = $allNodes->groupBy(
            fn ($item) => (string) ($item->parent_value ?? '')
        );

        /*
         * Find every descendant of the node being moved.
         *
         * Example:
         *
         * A
         * └── B
         *     └── C
         *
         * If B is moved, C is also a descendant.
         */
        $descendantValues = [];

        $collectDescendants = function (string $parentValue) use (
            &$collectDescendants,
            &$descendantValues,
            $childrenMap
        ) {
            $children = $childrenMap->get($parentValue, collect());

            foreach ($children as $child) {
                $childValue = (string) $child->value;

                if (in_array($childValue, $descendantValues, true)) {
                    continue;
                }

                $descendantValues[] = $childValue;

                $collectDescendants($childValue);
            }
        };

        $collectDescendants($nodeValue);

        /*
         * Prevent moving the node under one of its descendants.
         *
         * Example:
         *
         * A
         * └── B
         *     └── C
         *
         * Moving A under C would create:
         *
         * A -> B -> C -> A
         *
         * which is invalid.
         */
        if (in_array($newParentValue, $descendantValues, true)) {
            return back()
                ->withErrors([
                    'parent_value' =>
                        'The selected parent is a descendant of this node and cannot be used.',
                ])
                ->withInput();
        }

        /*
         * New level for the moved node.
         */
        $newLevel = (int) $parent->ilevel + 1;

        DB::connection('oracle')->transaction(function () use (
            $nodeValue,
            $newParentValue,
            $newLevel,
            $validated,
            $allNodes,
            $childrenMap
        ) {
            /*
             * Update only the fields that are editable
             * from the Edit screen.
             *
             * Technical fields remain unchanged.
             */
            DB::connection('oracle')
                ->table('ERP_SYSTEM_TREE')
                ->where('VALUE', $nodeValue)
                ->update([
                    'LABEL' => $validated['label'],
                    'LABEL_ENG' => $validated['label_eng'] ?? null,
                    'PARENT_VALUE' => $newParentValue,
                    'ILEVEL' => $newLevel,
                ]);

            /*
             * Recalculate levels of all descendants.
             *
             * We start with the moved node as the parent.
             */
            $levelMap = [
                $nodeValue => $newLevel,
            ];

            /*
             * Keep processing nodes until all descendants
             * have received their new level.
             */
            $queue = [$nodeValue];

            while (!empty($queue)) {
                $currentParentValue = array_shift($queue);

                $currentParentLevel =
                    $levelMap[$currentParentValue];

                $children = $childrenMap->get(
                    $currentParentValue,
                    collect()
                );

                foreach ($children as $child) {
                    $childValue = (string) $child->value;

                    /*
                     * Do not update the moved node itself
                     * as a child.
                     */
                    if ($childValue === $nodeValue) {
                        continue;
                    }

                    $childLevel = $currentParentLevel + 1;

                    DB::connection('oracle')
                        ->table('ERP_SYSTEM_TREE')
                        ->where('VALUE', $childValue)
                        ->update([
                            'ILEVEL' => $childLevel,
                        ]);

                    $levelMap[$childValue] = $childLevel;

                    $queue[] = $childValue;
                }
            }
        });

        /*
         * Clear TreeService cached data because the hierarchy
         * has changed.
         */
        $this->treeService->refresh();

        return redirect()
            ->route('admin.tree-nodes.index')
            ->with('success', 'Tree node updated successfully.');
    }

    /**
     * Delete a leaf node only.
     */
    public function destroy(string $id)
    {
        $node = $this->treeService->getNode($id);

        abort_if(!$node, 404);

        /*
         * Protect the actual root.
         */
        if ((string) $node->value === '1000000') {
            abort(403, 'Root node cannot be deleted.');
        }

        /*
         * Prevent deleting nodes that have children.
         */
        $children = $this->treeService->getChildren(
            $node->value
        );

        if ($children->isNotEmpty()) {
            return back()->with(
                'error',
                'Cannot delete this node because it has children.'
            );
        }

        /*
         * Query Builder is used because Eloquent delete
         * did not work correctly with this Oracle table.
         */
        $deleted = DB::connection('oracle')
            ->table('ERP_SYSTEM_TREE')
            ->where('VALUE', $node->value)
            ->delete();

        if (!$deleted) {
            return back()->with(
                'error',
                'The node could not be deleted.'
            );
        }

        /*
         * Clear cached tree data.
         */
        $this->treeService->refresh();

        return redirect()
            ->route('admin.tree-nodes.index')
            ->with(
                'success',
                'Tree node deleted successfully.'
            );
    }
}

